markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "/HappyLucky-UI"

version: 1.1.0

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/fatsheepcn/HappyLucky-UI.git
